name: flutter_showcase_nullsafety
description: A simple, fast and easy way to share you flutter project or mockups with the world.
version: 1.0.0
homepage: https://github.com/jamesblasco/flutter_showcase

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.17 
  font_awesome_flutter: ^9.2.0 
  layout: ^1.0.2
  equatable: ^2.0.3 
  dart_style: ^2.2.1 
  analyzer: ^2.8.0 
  _fe_analyzer_shared: ^31.0.0 
  args: ^2.3.0 
  yaml: ^3.1.0 

dev_dependencies:
  test: ^1.17.12
  flutter_test:
    sdk: flutter
  
  flutter_driver:
    sdk: flutter


flutter:

  assets:
    - assets/
